services:
  app:
    build:
      context: .
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        SOURCE_VERSION: ${SOURCE_VERSION}
    image: makeideas
    container_name: makeideas-container
    env_file:
      - ./webapp/.env
      - ./backend/.env
      - ./.env.docker
    ports:
      - '${PORT}:${PORT}'
